   
config_training:
    architecture: unet_attention
    patch_number: 20000
    patch_radius: 40
    model_name: Unet_attention_height_modeler_2
    n_epochs: 200
    lr: 0.001
    dropout: False #dropout = True yelds OOM issues (too much memory).